### ISSUE TITLE
No Well Actually Culture

### ISSUE THREAD

**Issue by jonleung** [hackedu/discussions#4]
Alex Kern sent me this article:
http://tirania.org/blog/archive/2011/Feb-17.html

Basically similar to Hacker School's no "well actually" culture. I'm not sure how similar or different is is to the "I question" or "I'm curious if". But one thing I just realized is that instead of saying, "we should try this", it could be phrased "I'm curious what happens if we do this"...

So I guess I'm curious if I say, "I'm curious what happens if we say I'm curious".

**Comment by MaxWofford** [comment]
:+1: I like this

**Comment by zachlatta** [comment]
Seems like we're really digging into semantics with this one. Agreed that we don't want any "well actually culture"—really like Recurse Center's perspective on this—but I want to be cautious of digging too far into semantics vs creating actual change.

**Comment by jonleung** [comment]
Agreed. I brought this up because I thought this specific language I was using was a blocking factor for other people on the team when I said lets do X?

**Comment by zachlatta** [comment]
I just skimmed through the article and I have to say I don't think this is the kind of writing I want to guide the organization with. My impression was that the article is essentially saying "you don't have friends because you _well actually_."

The article also seemed to have a much broader interpretation of what a "well actually" is. See the Recurse Center's article on it [here](https://www.recurse.com/manual#no-well-actuallys) for their definition.

Can you further articulate the similarity between a "well actually" and saying "I'm curious what happens if we do this" instead of "we should try this"? I'm having trouble seeing the relation.

Perhaps we should table this discussion.

**Comment by zachlatta** [comment]
Closing for now due to lack of responses.
